### PR TITLE
Implement `go install`

### PR DESCRIPTION
**Pull request by dhaiducek**
Addresses:
- https://github.com/stolostron/backlog/issues/21024

I also removed logic to check whether the file exists since it appears to be a fairly quick check for Go to see that it's installed and then we also won't have to worry about whether we have the correct version on our system.

I'm also curious whether `go get github.com/onsi/gomega/...` is even necessary in the `e2e-dependencies` target. I think we only need the binary since `gomega` is already in `go.mod`? I might try removing it if this initial commit works.

### CODE REVIEW

**Comment by dhaiducek** [comment]
Assuming this round of tests passes, this PR should be good to go for review.

**Review by gparvin — APPROVED** [review]

**Pull request merged**
